- name: C
  logo: C
  url: https://en.cppreference.com/w/c/language
  color: "#00a3e9"
  projects:
    - url: https://github.com/thehackersbrain/cpuinfo-os
    - url: https://github.com/thehackersbrain/gkernel
    - url: https://github.com/thehackersbrain/simple_web_server
    - url: https://github.com/thehackersbrain/curl_in_c
    - url: https://github.com/thehackersbrain/text-editor
    - url: https://github.com/thehackersbrain/passgen

- name: Python
  logo: Python
  url: https://www.python.org/
  color: "#3776AB"
  projects:
    - url: https://github.com/thehackersbrain/webhawk
    - url: https://github.com/thehackersbrain/hiddenpngpy
    - url: https://github.com/thehackersbrain/chat-room
    - url: https://github.com/thehackersbrain/networksniffer
    - url: https://github.com/thehackersbrain/port_scanner
    - url: https://github.com/thehackersbrain/linkparser
    - url: https://github.com/thehackersbrain/dirhunter
    - url: https://github.com/thehackersbrain/CVE-2021-41773

- name: x86 Assembly
  logo: Assembly
  color: "#111111"
  projects:
    - url: https://github.com/thehackersbrain/gbootloader

- name: Go
  logo: Go
  url: https://go.dev/
  color: "#00ADD8"
  projects:
    - url: https://github.com/ashleymavericks/rocket-server
    - url: https://github.com/ashleymavericks/titan-shell
    - url: https://github.com/ashleymavericks/dataload-db

- name: Flask
  logo: Flask
  url: https://flask.palletsprojects.com/en/2.1.x/
  color: "#000000"
  projects:
    - url: https://github.com/ashleymavericks/bitgrit-personality-api
    - url: https://github.com/ashleymavericks/tradingview-discord-middleware

- name: FastAPI
  logo: FastAPI
  url: https://fastapi.tiangolo.com/
  color: "#009688"
  projects:
    - url: https://github.com/ashleymavericks/browser-hot-reloading
    - url: https://github.com/ashleymavericks/strategical-trading
      wip: true

- name: Django
  logo: Django
  url: https://www.djangoproject.com/
  color: "#092E20"
  projects:
    - url: https://github.com/ashleymavericks/todo-list-battle
      wip: true

- name: TypeScript
  logo: TypeScript
  url: https://www.typescriptlang.org/
  color: "#3178C6"
  projects:
    - url: https://github.com/ashleymavericks/nextjs-starter-template
    - url: https://github.com/ashleymavericks/anuragsingh.dev
    - url: https://github.com/ashleymavericks/supabase-uptime-monitor

- name: JavaScript
  logo: JavaScript
  url: https://javascript.info/
  color: "#F7DF1E"
  projects:
    - url: https://github.com/ashleymavericks/unshorts

- name: Node.js
  logo: Node.js
  url: https://nodejs.org/en/
  color: "#339933"
  projects:
    - url: https://github.com/ashleymavericks/speaking-geo-assistant-backend
    - url: https://github.com/ashleymavericks/dietary-care

- name: Problem solving
  logo: LeetCode
  url: https://hackattic.com/u/ashleymavericks
  color: "#FFA116"
  projects:
    - url: https://github.com/ashleymavericks/leetcoding
    - url: https://github.com/ashleymavericks/hackerrank
    - url: https://github.com/ashleymavericks/hackattic
    - url: https://github.com/ashleymavericks/kata-log
    - url: https://github.com/ashleymavericks/sadservers
    - url: https://github.com/ashleymavericks/code.golf
    - url: https://github.com/ashleymavericks/deep-ml

- name: Spark AR
  logo: Spark AR
  url: https://sparkar.facebook.com/ar-studio/
  color: "#FF5C83"
  projects:
    - url: https://github.com/ashleymavericks/AR-PiZero

- name: Shell
  logo: GNU Bash
  url: https://www.gnu.org/
  color: "#4EAA25"
  projects:
    - url: https://github.com/ashleymavericks/dotfiles-public
