- name: C
  logo: C
  url: https://en.cppreference.com/w/c/language
  color: "#00a3e9"
  projects:
    - url: https://github.com/thehackersbrain/cpuinfo-os
    - url: https://github.com/thehackersbrain/gkernel
    - url: https://github.com/thehackersbrain/simple_web_server
    - url: https://github.com/thehackersbrain/curl_in_c
    - url: https://github.com/thehackersbrain/text-editor
    - url: https://github.com/thehackersbrain/passgen

- name: Python
  logo: Python
  url: https://www.python.org/
  color: "#3776AB"
  projects:
    - url: https://github.com/thehackersbrain/webhawk
    - url: https://github.com/thehackersbrain/hiddenpngpy
    - url: https://github.com/thehackersbrain/chat-room
    - url: https://github.com/thehackersbrain/networksniffer
    - url: https://github.com/thehackersbrain/camphish
    - url: https://github.com/thehackersbrain/rsa_decoder
    - url: https://github.com/thehackersbrain/thephisher
    - url: https://github.com/thehackersbrain/port_scanner
    - url: https://github.com/thehackersbrain/linkparser
    - url: https://github.com/thehackersbrain/dirhunter
    - url: https://github.com/thehackersbrain/CVE-2021-41773
    - url: https://github.com/thehackersbrain/maltego-transforms
    - url: https://github.com/thehackersbrain/django_blog

- name: ReactJS
  logo: React
  url: https://react.dev/
  color: "#61DAFB"
  projects:
    - url: https://github.com/thehackersbrain/hookbank
    - url: https://github.com/thehackersbrain/snapgram

- name: NextJS
  logo: Next.js
  url: https://nextjs.org/
  color: "#000000"
  projects:
    - url: https://github.com/thehackersbrain/brainwave
    - url: https://github.com/thehackersbrain/minimal-portfolio
    - url: https://github.com/thehackersbrain/carepulse

- name: Rust
  logo: Rust
  url: https://google.com/search?q=assembly+lang
  color: "#000000"
  projects:
    - url: https://github.com/thehackersbrain/chip8
    - url: https://github.com/thehackersbrain/hiddenpng
    - url: https://github.com/thehackersbrain/passcraft
    - url: https://github.com/thehackersbrain/ctftimers

- name: Flutter
  logo: Flutter
  url: https://flutter.dev/
  color: "#02569B"
  projects:
    - url: https://github.com/thehackersbrain/flutternews

- name: x86 Assembly
  logo: AssemblyScript
  url: https://google.com/search?q=assembly+lang
  color: "#111111"
  projects:
    - url: https://github.com/thehackersbrain/gbootloader

- name: Go
  logo: Go
  url: https://go.dev/
  color: "#00ADD8"
  projects:
    - url: https://github.com/thehackersbrain/netscan
    - url: https://github.com/ashleymavericks/titan-shell
    - url: https://github.com/ashleymavericks/dataload-db

- name: C++
  logo: C++
  url: https://google.com/search?q=cpp+lang
  color: "#00599C"
  projects:
    - url: https://github.com/thehackersbrain/hiddenwave

- name: Problem solving
  logo: LeetCode
  url: https://hackattic.com/u/ashleymavericks
  color: "#FFA116"
  projects:
    - url: https://github.com/ashleymavericks/leetcoding
    - url: https://github.com/ashleymavericks/hackerrank
    - url: https://github.com/ashleymavericks/hackattic
    - url: https://github.com/ashleymavericks/kata-log
    - url: https://github.com/ashleymavericks/sadservers
    - url: https://github.com/ashleymavericks/code.golf
    - url: https://github.com/ashleymavericks/deep-ml

- name: Shell
  logo: GNU Bash
  url: https://www.gnu.org/
  color: "#4EAA25"
  projects:
    - url: https://github.com/thehackersbrain/saycheese_v2.0

- name: LaTeX
  logo: LaTeX
  url: https://www.latex-project.org/
  color: "#008080"
  projects:
    - url: https://github.com/thehackersbrain/resume
    - url: https://github.com/thehackersbrain/fiction-book-template

- name: Docker
  logo: Docker
  url: https://docker.com
  color: "#2496ED"
  projects:
    - url: https://github.com/thehackersbrain/kalivnc
    - url: https://github.com/thehackersbrain/archvnc
